46044 Review, test and release update for HubSpot (Forms) 15
umbraco/Umbraco.Forms.Integrations pull request #114
Opened 2024-11-28 09:15 UTC by dtng95

- Update Hubspot reference to CMS and Forms 15
- update client reference to backoffice 15

2024-11-28 09:19 UTC, AndyButland approved these changes

2024-11-29 16:09 UTC, acoumb requested changes
* Update package version to `6.0.0` in `Client > public > umbraco-package.json`
* With version 15, there is a console warning, so could you update the extension type in `umbraco-package.json` to use `backofficeEntryPoint`?
```
The `entryPoint` extension-type is deprecated, please use the `backofficeEntryPoint`.`
```

2024-11-29 16:09 UTC, acoumb commented on src/Umbraco.Forms.Integrations.Crm.Hubspot/Umbraco.Forms.Integrations.Crm.Hubspot.csproj
> +		<PackageReference Include="Umbraco.Cms.Core" Version="15.0.0" />
These should also be as interval `[15.0.0,16)`.

2024-12-02 08:28 UTC, AndyButland approved these changes

2024-12-02 09:41 UTC, merged